In [1]:
#Provides the multidimensional array objects

In [2]:
import numpy

In [4]:
n=numpy.arange(27)

In [5]:
n

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [6]:
type(n)

numpy.ndarray

In [7]:
n.reshape(3,9)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26]])

In [8]:
n.reshape(3,3,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [9]:
#That was a 3-dimensional array above -^

In [10]:
m=numpy.asarray([[123,12,123,12,33],[],[]])

In [11]:
m


array([list([123, 12, 123, 12, 33]), list([]), list([])], dtype=object)

In [12]:
type(m)

numpy.ndarray

In [13]:
import cv2

In [14]:
#We are going to work with pixels with numpy arrays below:

In [18]:
img_grey=cv2.imread("smallgray.png", 0)

In [19]:
img_grey

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [20]:
#Mention that if the file entered incorrectly, you will receive nothing

In [23]:
#This is the image in BGR format in gray-scale

In [24]:
img_grey=cv2.imread("smallgray.png", 1)

In [25]:
#This's the colourful result

In [26]:
img_grey

array([[[187, 187, 187],
        [158, 158, 158],
        [104, 104, 104],
        [121, 121, 121],
        [143, 143, 143]],

       [[198, 198, 198],
        [125, 125, 125],
        [255, 255, 255],
        [255, 255, 255],
        [147, 147, 147]],

       [[209, 209, 209],
        [134, 134, 134],
        [255, 255, 255],
        [ 97,  97,  97],
        [182, 182, 182]]], dtype=uint8)

In [27]:
#So, we created a numpy array out of the image

In [28]:
# How to create an image out of the array? ;)


In [31]:
cv2.imwrite("newsmallgray.png", img_grey)

True

In [32]:
# Success - image newsmallgray.png is stored in the default folder

In [33]:
a=[1,2,3]

In [34]:
#Indexing, slicing and iterating

In [35]:
img_grey[0:2]

array([[[187, 187, 187],
        [158, 158, 158],
        [104, 104, 104],
        [121, 121, 121],
        [143, 143, 143]],

       [[198, 198, 198],
        [125, 125, 125],
        [255, 255, 255],
        [255, 255, 255],
        [147, 147, 147]]], dtype=uint8)

In [36]:
img_grey=cv2.imread("smallgray.png", 0)

In [37]:
img_grey

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [38]:
img_grey[0:2]

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147]], dtype=uint8)

In [39]:
img_grey[0:2,2:4]

array([[104, 121],
       [255, 255]], dtype=uint8)

In [41]:
for i in img_grey:
    print(i)

[187 158 104 121 143]
[198 125 255 255 147]
[209 134 255  97 182]


In [42]:
#If you want iterate with columns, you should use transpose method like blow:

In [43]:
for i in img_grey.T:
    print(i)

[187 198 209]
[158 125 134]
[104 255 255]
[121 255  97]
[143 147 182]


In [44]:
# If you need to iterate value by value, you'll need flat property:


In [45]:
for i in img_grey.flat:
    print(i)

187
158
104
121
143
198
125
255
255
147
209
134
255
97
182


In [47]:
#Stacking(concatenating) and splitting the numpy arrays

In [48]:
ims=numpy.hstack(img_grey, img_grey)

TypeError: hstack() takes 1 positional argument but 2 were given

In [49]:
#We do tupple to avoid the error

In [59]:
imc=numpy.hstack((img_grey, img_grey, img_grey))

In [60]:
imc

array([[187, 158, 104, 121, 143, 187, 158, 104, 121, 143, 187, 158, 104,
        121, 143],
       [198, 125, 255, 255, 147, 198, 125, 255, 255, 147, 198, 125, 255,
        255, 147],
       [209, 134, 255,  97, 182, 209, 134, 255,  97, 182, 209, 134, 255,
         97, 182]], dtype=uint8)

In [54]:
# This was the horizontal concatenation above

In [55]:
# Below we can see the vertical concatenation:

In [56]:
ims=numpy.vstack((img_grey, img_grey, img_grey))

In [57]:
ims

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182],
       [187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182],
       [187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [61]:
lst=numpy.hsplit(ims,5)

In [62]:
lst

[array([[187],
        [198],
        [209],
        [187],
        [198],
        [209],
        [187],
        [198],
        [209]], dtype=uint8), array([[158],
        [125],
        [134],
        [158],
        [125],
        [134],
        [158],
        [125],
        [134]], dtype=uint8), array([[104],
        [255],
        [255],
        [104],
        [255],
        [255],
        [104],
        [255],
        [255]], dtype=uint8), array([[121],
        [255],
        [ 97],
        [121],
        [255],
        [ 97],
        [121],
        [255],
        [ 97]], dtype=uint8), array([[143],
        [147],
        [182],
        [143],
        [147],
        [182],
        [143],
        [147],
        [182]], dtype=uint8)]

In [64]:
lst2=numpy.vsplit(ims,3)

In [65]:
lst2

[array([[187, 158, 104, 121, 143],
        [198, 125, 255, 255, 147],
        [209, 134, 255,  97, 182]], dtype=uint8),
 array([[187, 158, 104, 121, 143],
        [198, 125, 255, 255, 147],
        [209, 134, 255,  97, 182]], dtype=uint8),
 array([[187, 158, 104, 121, 143],
        [198, 125, 255, 255, 147],
        [209, 134, 255,  97, 182]], dtype=uint8)]

In [66]:
# this was horizontal and vertical splitting of the numpy arrays

In [67]:
lst2[0]

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)